name: Build Tauri App on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install pkg-config via Chocolatey
        run: choco install pkgconfiglite --yes

      - name: Verify pkg-config installation
        run: pkg-config --version

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      - name: Install OpenCV
        run: .\vcpkg\vcpkg.exe install opencv4:x64-windows

      - name: Configure vcpkg environment
        run: |
          setx VCPKG_ROOT "%cd%\vcpkg"
          setx PATH "%PATH%;%cd%\vcpkg\installed\x64-windows\bin"

      - name: Test pkg-config
        run: pkg-config --cflags opencv4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TauriApp
          path: ./dist/x86_64-pc-windows-msvc.exe
