name: Build Tauri App on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23" # 根据你的项目需求设置 Node.js 版本

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build -- --target x86_64-pc-windows-msvc

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: TauriApp
          path: ./dist/x86_64-pc-windows-msvc.exe # 根据实际生成的文件路径调整
