name: Build Tauri App on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"

      - name: Install llvm and opencv via Chocolatey
        run: |
          choco install llvm --version=15.0.0 -y
          choco install opencv --version=4.5.5 -y

      - name: Set OpenCV environment variables
        run: |
          $opencvDir = "C:\tools\opencv"
          $includePaths = Join-Path -Path $opencvDir -ChildPath "build\include"
          $linkLibs = Join-Path -Path $opencvDir -ChildPath "build\x64\vc15\lib\opencv_world455.lib"
          $linkPaths = Join-Path -Path $opencvDir -ChildPath "build\x64\vc15\lib"
          echo "OPENCV_INCLUDE_PATHS=$includePaths" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_LIBS=$linkLibs" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_PATHS=$linkPaths" >> $env:GITHUB_ENV

      - name: Build and Test
        run: |
          echo "Include Paths: $env:OPENCV_INCLUDE_PATHS"
          echo "Link Libs: $env:OPENCV_LINK_LIBS"
          echo "Link Paths: $env:OPENCV_LINK_PATHS"

      - name: Verify OpenCV Installation
        run: |
          dir "C:\tools\opencv"
          dir "C:\tools\opencv\build\include"
          dir "C:\tools\opencv\build\x64\vc15\lib"
          dir "C:\tools\opencv\build\x64\vc15\bin"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build

      - name: Copy OpenCV DLL
        run: |
          copy "C:\tools\opencv\build\x64\vc15\bin\opencv_world455.dll" "./src-tauri/target/release"

      - name: Verify build output
        run: |
          echo "Checking build output:"
          dir ./src-tauri/target/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TauriApp
          path: ./src-tauri/target/release/*.exe
