name: windows-build-on-release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Venv init
        run: |
          cd ./src-tauri
          python -m venv .venv
      - name: Venv check
        run: |
          dir ./src-tauri
          dir ./src-tauri/.venv

      - name: maturin init
        run: |
          cd ./src-tauri
          pip install maturin
          pip freeze

      - name: maturin check
        run: |
          maturin --version
          dir ./src-tauri/.venv

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install llvm, vcredist140 and opencv via Chocolatey
        run: |
          choco install vcredist140 -y
          choco install llvm --version=18.1.8 -y
          choco install opencv --version=4.10.0 -y

      - name: Verify Microsoft Visual C++ Installation
        run: |
          dir "C:\Windows\System32\*.dll"

      - name: Verify OpenCV Installation
        run: |
          dir "C:\tools\opencv"
          dir "C:\tools\opencv\build\include"
          dir "C:\tools\opencv\build\x64"
          dir "C:\tools\opencv\build\x64\vc16\lib"
          dir "C:\tools\opencv\build\x64\vc16\bin"

      - name: Set OpenCV environment variables
        run: |
          $opencvDir = "C:\tools\opencv"
          $includePaths = Join-Path -Path $opencvDir -ChildPath "build\include"
          $linkLibs = Join-Path -Path $opencvDir -ChildPath "build\x64\vc16\lib\opencv_world4100.lib"
          $linkPaths = Join-Path -Path $opencvDir -ChildPath "build\x64\vc16\lib"
          echo "OPENCV_INCLUDE_PATHS=$includePaths" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_LIBS=$linkLibs" >> $env:GITHUB_ENV
          echo "OPENCV_LINK_PATHS=$linkPaths" >> $env:GITHUB_ENV

      - name: Verify OpenCV environment variables
        run: |
          echo "Include Paths: $env:OPENCV_INCLUDE_PATHS"
          echo "Link Libs: $env:OPENCV_LINK_LIBS"
          echo "Link Paths: $env:OPENCV_LINK_PATHS"

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run tauri build

      - name: Copy OpenCV DLL
        run: |
          copy "C:\tools\opencv\build\x64\vc16\bin\opencv_world4100.dll" "./src-tauri/target/release"

      - name: Copy vcredist140 DLL
        run: |
          copy "C:\Windows\System32\msvcp140.dll" "./src-tauri/target/release"
          copy "C:\Windows\System32\concrt140.dll" "./src-tauri/target/release"
          copy "C:\Windows\System32\vcruntime140.dll" "./src-tauri/target/release"
          copy "C:\Windows\System32\vcruntime140_1.dll" "./src-tauri/target/release"

      - name: maturin build
        run: |
          cd ./src-tauri
          maturin build --release

      - name: maturin build check
        run: |
          dir ./src-tauri/target
          dir ./src-tauri/target/wheels

      - name: Copy wheels
        run: |
          copy "./src-tauri/target/wheels/kiwi-0.1.0-cp310-abi3-win_amd64.whl" "./src-tauri/target/release"

      - name: Verify build output
        run: |
          echo "Checking build output:"
          dir ./src-tauri/target/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kiwi
          path: |
            ./src-tauri/target/release/*.exe
            ./src-tauri/target/release/*.dll
            ./src-tauri/target/release/*.whl
